name: InfoBook
version: 1.0
author: QuiverlyRivalry
api: 3.0.0
main: InfoBook\Main
description: Gives a book on command!
permissions:
 book.command:
  default: true
commands:
 book:
  description: Gives the infobook
